#!/bin/sh -e
install -v -d -m755 $1/usr/share/xml/docbook/xml-dtd-4.5
install -v -d -m755 $1/etc/xml
unzip docbook-xml-4.5.zip
cp -v -af docbook.cat *.dtd ent/ *.mod \
    $1/usr/share/xml/docbook/xml-dtd-4.5

