#!/bin/sh -e
patch -Np1 -i docbook-xsl-nons-1.79.2-stack_fix-1.patch
install -v -m755 -d $1/usr/share/xml/docbook/xsl-stylesheets-nons-1.79.2 &&

cp -v -R VERSION assembly common eclipse epub epub3 extensions fo        \
         highlighting html htmlhelp images javahelp lib manpages params  \
         profiling roundtrip slides template tests tools webhelp website \
         xhtml xhtml-1_1 xhtml5                                          \
    $1/usr/share/xml/docbook/xsl-stylesheets-nons-1.79.2 &&

ln -s VERSION $1/usr/share/xml/docbook/xsl-stylesheets-nons-1.79.2/VERSION.xsl &&

install -v -m644 -D README \
                    $1/usr/share/doc/docbook-xsl-nons-1.79.2/README.txt &&
install -v -m644    RELEASE-NOTES* NEWS* \
                    $1/usr/share/doc/docbook-xsl-nons-1.79.2
